### PR TITLE
Feedback note popup

### PR DESCRIPTION
**Pull request by emcelroy**
PT Story: https://www.pivotaltracker.com/story/show/176161785

[#176161785]

* Feedback note button has default, hover, and selected states
* When button is clicked, open popup dialog
* Popup has a button to close the popup that reads "Got it" with default, hover, and pressed states

### CODE REVIEW

**Review by mklewandowski — APPROVED** [review]
👍 This looks great to me!  The only thing I wonder is should the note button itself have an active state when pressed?  I looked in the UI spec and didn't find anything, but knowing Michael, it would probably use the same colors that are used when the modal is showing (green background, white text).

**Comment by mklewandowski** [comment]
Looks like the prototype does have an active style of the note button:
image

**Comment by emcelroy** [comment]
Thanks, @mklewandowski. There is an `active` class for that button in the code. You can see the style rules in css/portal-dashboard/feedback/feedback-note-toggle.less starting on line 20. The class is applied if the boolean `buttonActive` is true in js/components/portal-dashboard/feedback/feedback-note-toggle.tsx (lines 15, 18, 23). It works (see GIF), but is how I did that maybe not as straightforward as it could be?

active-state

Also, I switched this PR back to a draft because of a coverage problem that showed up after I merged in master. I'm having a little trouble tracking that down. Hopefully I can get that figured out today.

**Comment by mklewandowski** [comment]
> Thanks, @mklewandowski. There is an `active` class for that button in the code. You can see the style rules in css/portal-dashboard/feedback/feedback-note-toggle.less starting on line 20. The class is applied if the boolean `buttonActive` is true in js/components/portal-dashboard/feedback/feedback-note-toggle.tsx (lines 15, 18, 23). It works (see GIF), but is how I did that maybe not as straightforward as it could be?
> 
> 
> 
> Also, I switched this PR back to a draft because of a coverage problem that showed up after I merged in master. I'm having a little trouble tracking that down. Hopefully I can get that figured out today.

Right, I see it working when the popup is showing.  That looks good.  But based on the prototype, it also looks like the state should change when the mouse is down over the button before the popup has shown (which is typical with Michael's specs - a mouse hover and mouse down state).  We just need to add some CSS that uses the :active pseudo class to get this behavior.

**Comment by emcelroy** [comment]
Oh, I see. Thanks for catching that missing nuance. I've added it with the latest commit.

**Review by mklewandowski — APPROVED** [review]
👍 Looks good!  Thanks for the fix!

**Pull request merged**
